// automatically generated by the FlatBuffers compiler, do not modify
/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */
export var Status;
(function (Status) {
    Status[Status["Alert"] = 0] = "Alert";
    Status[Status["Homing"] = 1] = "Homing";
    Status[Status["Idle"] = 2] = "Idle";
    Status[Status["Jogging"] = 3] = "Jogging";
})(Status || (Status = {}));
